# Use root/example as user/password credentials
version: '3.1'

services:
  app: 
    image: abunasyr/node-web-app
    ports: 
      - 3000:3000
  mongo:
    image: mongo
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - 27017:27017
